#!/usr/bin/bash
# Remove all <none> images

if [[ $(docker images -f "dangling=true" -q) ]]
then
    docker rmi $(docker images -f "dangling=true" -q)
    echo "DONE"
else
    echo "Cannot find any <none> images"
fi
